### ISSUE TITLE
Sym links are not followed

### ISSUE THREAD

**Issue by KornelH** [erlang-ls/erlang_ls#1064]
**Describe the bug**
Some build systems (e.g. [Bazel](https://bazel.build/)) places generated files outside of the workspace/project/repository and symlink those one way or another (e.g. Bazel creates a symlink `bazel-bin` from the workspace). Erlang header files could be generated there therefore I add those directories to the `include_dirs` configuration, e.g. `bazel-bin/.../inclulde`. Erlang-ls doesn't recognize the HRL files in these generated and linked directories.

**To Reproduce**
I created a dummy setup like below:
```
.
├── build_generated
│   └── group_a
│       └── mylib
│           └── gen
│               └── include
│                   └── person.hrl
└── under_version_control
    ├── build_generated -> ../build_generated
    ├── erlang_ls.config
    └── group_a
        └── mylib
            ├── include
            │   └── vehicle.hrl
            └── src
                ├── mylib.app.src
                └── mylib.erl
```
Files are very simple, `under_version_control/group_a/mylib` was generated by command `rebar3 new lib` and removed the not relevant files.

person.hrl:
```erlang
-record(person, {
        name :: string()
        }).
```

vehicle.hrl:
```erlang
-record(vehicle, {
        type :: atom(),
        passengers,
        color = "red"
        }).
```

mylib.erl:
```erlang
-module(mylib).

-export([f/0]).

-include("person.hrl").
-include("vehicle.hrl").

f() ->
    [#person{name = "Paul McCartney"},
     #vehicle{type = submarine,
              passengers = 4,
              color = "yellow"}
    ].
```

erlang_ls.config:
```yaml
otp_path: "/repo/ekorhor/usr/otp"
apps_dirs:
  - "group_a/*"
diagnostics:
  disabled:
    - crossref
    - dialyzer
    - elvis
include_dirs:
  - "group_a/*/include"
  - "build_generated/group_a/mylib/gen/include"
lenses:
  enabled:
    - server-info
  disabled:
    - ct-run-test
    - show-behaviour-usages
```

Please find the complete example attached as [erlang_ls_dont_follow_symlinks.tar.gz](https://github.com/erlang-ls/erlang_ls/files/6818909/erlang_ls_dont_follow_symlinks.tar.gz).

If `build_generated` is symlinked from under `under_version_control` then in file `mylib.erl` I get an error messages:

- _"can't find include file "person.hrl""_ at line `-include("person.hrl").` and
- _"record person undefined"_ at record usage.

If I copy `build_generated` under `under_version_control` instead of symlinking then everything works perfectly.

**Expected behavior**
Follow include directories even if those are symlinks.

**Actual behavior**
Symlinks are not followed, HRL files reside in symlinked include directories are not found.

**Context**
 - `erlang_ls` version (tag/sha): I don't know, I use [erlang-ls/vscode](https://github.com/erlang-ls/vscode) v0.0.27
 - Editor used: Visual Studio Code 1.58.0 on Windows 10, Remote Development to Ubuntu 16.04 LTS
 - LSP client used: [erlang-ls/vscode](https://github.com/erlang-ls/vscode) v0.0.27
