### ISSUE TITLE
can't find include lib "proper/include/proper.hrl"

### ISSUE THREAD

**Issue by astutecat** [erlang-ls/erlang_ls#1103]
Hi,

I'm not 100% what's going on here but I am having trouble including proper in a simple test case. The extension is failing with 'can't find include lib "proper/include/proper.hrl"', when the CLI is perfectly happy to compile and run the test case in question.

My erlang_ls.config:

```
otp_path: "/Users/astutecat/.asdf/installs/erlang/23.1.1"
include_dirs:
  - "include/"
  - "_build/*/lib"
  - "_build/*/lib/*/include"
deps_dirs:
  - "_build/*/lib/*"
diagnostics:
  enabled:
    - compiler
    - dialyzer
  disabled:
    # Disable xref because it struggles with parse transform, like lager functions.
    - xref
lenses:
  enabled:
    - ct-run-test
    - show-behaviour-usages
```

my rebar.config:

```
{erl_opts, [debug_info]}.
{deps, []}.

%% the plugin itself
{project_plugins, [rebar3_proper]}.
%% The PropEr dependency is required to compile the test cases
%% and will be used to run the tests as well.
{profiles,
    [{test, [
        {deps, [
            %% hex
            {proper, "1.3.0"}
        ]}
    ]}
]}.
```

The file where the error is happening is in `test/dog_sketch_test.erl` and has this content:

```
-module(prop_dog_sketch).

-include_lib("proper/include/proper.hrl").

prop_test() ->
    ?FORALL(Type, (mytype()), begin boolean(Type) end).

boolean(_) -> true.

mytype() -> term().

```

The thing is, the include files definitely are in `_build/test/lib/proper/include` but it seems erlang_ls in VSCode is having trouble finding them.

Any ideas on what is wrong here? At first I thought it was to do with my configuration somewhere but I can't see where it would be having trouble.
