### ISSUE TITLE
Allow configuration of LSP providers

### ISSUE THREAD

**Issue by the-mikedavis** [erlang-ls/erlang_ls#1310]
**Is your feature request related to a problem? Please describe.**

Some providers like signature help (#1300, #1307) may be experimental at first and should be disabled by default. Alternatively, an erlang_ls user might want to disable some providers if they find them distracting or if there's a bug with a provider in a given project. Whether any provider is enabled should be configurable with the default that all stable providers be enabled.

**Describe the solution you'd like**

This will take a bit of work in `els_provider` and `els_config` to parse new configuration and then some work in `els_general_provider` to form the ServerCapabilities message around the configured providers. This configuration could look like so:

```yaml
providers:
  enabled:
    - signature-help
```

or maybe

```yaml
providers:
  signature-help: true # defaults to `false`
  completion: false # defaults to `true`
```

**Describe alternatives you've considered**

Currently we can get around this by making manual edits to `els_general_provider`, but this is on a per-server basis instead of per-project.

**Additional context**

See https://github.com/erlang-ls/erlang_ls/pull/1307#issuecomment-1134846480
