### ISSUE TITLE
Make file name references absolute when indexing

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#408]
**Describe the bug**

If you have an `erlang_ls.config` with relative paths in it, e.g.

```yaml
include_dirs:
  - "include"
  - "../"
deps_dirs:
  - "../sibling_project"
```  
then references to functions from `../sibling_project` end up having a path with the `../` in it. Go to definition in vscode then works, but starting the language server in the sibling project does not work properly.

**To Reproduce**

As described above

**Expected behavior**

When files are opened, and the `erlang_ls` server starts up, all paths are absolute, so there is no confusion.

**Actual behavior**

As described above

**Context**
 - `erlang_ls` version (tag/sha): fe765af40932d593367786bc41c65d5327e9757d
 - Editor used: vscode
 - LSP client used: erlang_ls
