### ISSUE TITLE
Be able to disable diagnostics

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#656]
In #652 we enabled the user to customize diagnostics. It is often the case that one may want to disable a specific diagnostic. I propose we slightly modify the diagnostics block of the config format to support something like:

```
diagnostics:
  enabled:
    - xref
  disabled:
    - elvis
```

The above would start from the default diagnostics, add the enabled ones (adding an already enabled diagnostics will be a noop) and remove the disabled ones.
