### ISSUE TITLE
include_lib not found for rebar3 dependencies

### ISSUE THREAD

**Issue by Elhodred** [erlang-ls/erlang_ls#773]
**Describe the bug**
I created a project using rebar3 with some dependencies like nksip.
adding  `-include_lib("nkserver/include/nkserver_module.hrl").` to a module raises a compiler error: [Compiler] [E] can't find include lib "nkserver/include/nkserver_module.hrl"
The module is fine and compiles correctly, is just erlang_ls complaining abut the include lib.

This is my erlang_ls.config:
```
otp_path: "/usr/local/Cellar/erlang/22.2.1/lib/erlang"
deps_dirs:
  - "lib/*"
  - "_build/default/lib/*"
diagnostics:
  enabled:
    - xref
  disabled:
    - dialyzer
include_dirs:
  - "include"
lenses:
  enabled:
    - ct-run-test
    - server-info
macros:
  - name: DEFINED_WITH_VALUE
    value: 42
  - name: DEFINED_WITHOUT_VALUE
```

**To Reproduce**
Just create a rebar3 application, add a dependency like nksip, create a module and add `-include_lib("nkserver/include/nkserver_module.hrl").` (or whichever dependency you want to test). Get dependencies or compile the project to make rebar fetch the dependencies.

**Expected behavior**
Don't raise any error for include_libs that comes from dependencies added to rebar.config.

**Actual behavior**
Detect correctly the includes from rebar3 dependencies.

**Context**
 - `erlang_ls` version (tag/sha): 0.4.1
 - Editor used: NVIM v0.4.3
 - LSP client used: coc-erlang_ls

**Comment by robertoaloi** [comment]
Hi @Elhodred 

The correct config should contain:

```
deps_dirs:
  - "_build/default/lib/*"
include_dirs:
  - "_build/default/lib/*/include"
  - "include"
```

It's not obvious, but this manual config should just disappear once the integration with rebar3 is complete.

Can you try the above and verify it works for you? Thanks.

**Comment by Elhodred** [comment]
Hi @robertoaloi

Unfortunately, it doesn't seem to work. I already tried that and it didn't work. I tried again just in case and nothing.I'm not sure if I'm missing something else.
Here is my new config:

```
otp_path: "/usr/local/Cellar/erlang/22.2.1/lib/erlang"
deps_dirs:
  - "_build/default/lib/*"
diagnostics:
  enabled:
    - xref
  disabled:
    - dialyzer
include_dirs:
  - "_build/default/lib/*/include"
  - "include"
lenses:
  enabled:
    - ct-run-test
	- server-info
macros:
  - name: DEFINED_WITH_VALUE
    value: 42
  - name: DEFINED_WITHOUT_VALUE
```
Thanks for your answer
