### ISSUE TITLE
compiler diagnostics do not find transitive dependencies.

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#777]
**Describe the bug**

If a file implements a behaviour, and that behaviour in turn implements another one, the diagnostics `load_dependency` function does not load the second one, so we report spurious warnings.

**Context**
 - `erlang_ls` version (tag/sha): 9e5034e9359971e5ffa61771b0d70d47fc5b2209
 - Editor used:
 - LSP client used:

**Comment by robertoaloi** [comment]
@alanz Do you have a minimal reproducible example for this? Also see PR #848 .

**Comment by robertoaloi** [comment]
@alanz Closing for now, in the attempting of having a more focused backlog. Feel free to re-open once you come up with a reproducible example.

**Comment by eproxus** [comment]
I _think_ I may have the same issue. I have a module, `ws_json` implementing a custom behavior ( also in `src/`) and that behaviour in turn implements the behavior `cowboy_websocket`. I get this warning:

```
examples/ws/src/ws_json.erl:
    3:1   warning Issue in included file (3): behaviour cowboy_websocket undefined ​Compiler
```

I tried hard to coax `erlang_ls` into finding all behaviors with this config:

```yaml
apps_dirs:
  - "."
  - "examples"
deps_dirs:
  - "_build/default/lib/*"
  - "_build/default/checkouts/*"
include_dirs:
  - "_build/default/lib/*/include"
  - "_checkouts/*/include"
code_path_extra_dirs:
  - "_build/default/lib/*/ebin"
```

If I remove `code_path_extra_dirs` I get many more similar errors (I have several different behavior chains wrapping Cowboy behaviors). However, the error above I can't get rid of no matter how much I try. The Cowboy behaviors all exist and are in their respective `ebin` and `src` directories under `_build/default/lib/cowboy` and they work fine.
