### ISSUE TITLE
Cannot find definition for functions defined in OTP

### ISSUE THREAD

**Issue by onno-vos-dev** [erlang-ls/erlang_ls#928]
**Describe the bug**
I suspect a regression happened due to the introduction of https://github.com/erlang-ls/erlang_ls/pull/881 even though I have not been able to confirm it. Something happened between 0.9.0 and 0.10.0 at least as this issue is not present in 0.9.0. In many modules that I operate I get random warnings that Erlang LS fails to find the definition of functions that are defined in OTP. Due to this, hot code reload is broken and my workflow (in which I heavily depend on hot code reloading for my day to day coding) is broken. 

**To Reproduce**
I've failed to produce a small enough testcase which confirms the issue and it seems to happen occasionally but not every time. Jumping to the `ordsets` module and re-loading the module which previously complained about `ordsets:subtract/2` not being found fixes the issue which seems to point to a lack of POIs from OTP. 

```
Cannot find definition for function ordsets:subtract/2
```

**Expected behavior**
Expect Erlang LS to find the definition of ordsets:subtract/2. 

**Context**
 - `erlang_ls` version (tag/sha): 0.10.0
 - Editor used: Visual Code Studio 1.53.2
 - LSP client used: ? (Extension used)

**erlang_ls.config**
```
otp_path: "<otp_path>"
plt_path: "<plt_path>"
diagnostics:
  enabled:
    - compiler
    - crossref
    - dialyzer
    - elvis
    - bound_var_in_pattern
    - unused_includes
    - unused_macros
deps_dirs:
  - "lib/*"
include_dirs:
  - "lib/*/include"
  - "lib/*/src"
  - "lib"
macros:
  - name: APPLICATION
code_reload:
  node: kred@<hostname>
```
